set -a
SECRETS_PATH="${SECRETS_PATH:-../react-native-test-ci-secrets}"
. $SECRETS_PATH/release.env
ORG_GRADLE_PROJECT_UPLOAD_STORE_FILE="../../$SECRETS_PATH/$UPLOAD_STORE_FILE"
ORG_GRADLE_PROJECT_UPLOAD_KEY_ALIAS=$UPLOAD_KEY_ALIAS
ORG_GRADLE_PROJECT_UPLOAD_STORE_PASSWORD=$UPLOAD_STORE_PASSWORD
ORG_GRADLE_PROJECT_UPLOAD_KEY_PASSWORD=$UPLOAD_KEY_PASSWORD
set +a
