name: Test

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4

      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - run: npm test
